# Generated by Django 5.1.5 on 2025-01-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fashionCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fashionCategory/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
